[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { path = "../aoc" }
fxhash = "0.2.1"
itertools = "0.13.0"
log = "0.4.22"
rayon = "1.10.0"
regex = "1.11.1"
simplelog = "0.12.2"
